### ISSUE TITLE
very long qnames are not processed correctly

### ISSUE THREAD

**Issue by pspacek** [DNS-OARC/dnsperf#135]
- Version: 2.4.2, x86_64, Arch Linux
- Query sample: https://www.dns-oarc.net/files/dnsperf/data/queryfile-example-10million-201202.gz
- Example query: qname present in the sample query data set, line 841810
```
api-read.facebook.com.\002\004\003\002\002\002\002\005\004\004\003\004\006\005\006\006\006\005\006\006\006\007\009\008\006\007\009\007\006\006\008\011\008\009\010\010\010\010\010\006\008\011\012\011\010\012\009\010\010\010\255\219. A
```

Error message:
```
Warning: invalid domain name (or out of space): api-read.facebook.com.\002\004\003\002\002\002\002\005\004\004\003\004\006\005\006\006\006\005\006\006\006\007\009\008\006\007\009\007\006\006\008\011\008\009\010\010\010\010\010\006\008\011\012\011\010\012\009\010\010\010\255\219.
```

As far as I can tell this is valid query withing protocol-permitted limits. dnspython parses it just fine, wire length 84 bytes.

**Comment by jelu** [comment]
This is not a problem with long names, but an issue with quoting which was lost when removing internal bind libraries.

Can you test https://github.com/jelu/dnsperf/tree/dname-quotes ?
