### ISSUE TITLE
accepted QTYPE strings

### ISSUE THREAD

**Issue by vcunat** [DNS-OARC/dnsperf#145]
[Recently](https://github.com/DNS-OARC/dnsperf/commit/7c3f51ca3847b9f37d0a547a5f1d80c47aa09511#diff-7433c714c0b715f5f139145dedf39bec6dd905f35abeffc1c625cda4685d8e0b) the set of accepted QTYPE strings changed and my old query-set (generated from real traffic) has lots of cases that get skipped now.  Issues I see:
 - accepting `*` instead of `ANY`, and meaningless `Reserved` and `Unassigned`
   (yes, the IANA table can't be used blindly)
 - missing `TYPE123`

One way of dealing with this would be [using ldns](https://github.com/vcunat/dnsperf/commit/d546b9f973b42); fixing these directly shouldn't need that much code changes either.
- - -
_I see my query-set even contains some `TYPE0` which would need additional code due to unrepresentability in ldns API, but I think it's fine to drop that weird case._

**Comment by jelu** [comment]
Thanks, another thing missed when removing BINDs internal development libraries.

I've added own parsing of TYPE to support basic DNS without LDNS.

Please test develop branch / pre-release packages again.
