### ISSUE TITLE
Anyway to specify the real client ip like dig -subnet option in this tool?

### ISSUE THREAD

**Issue by hdw868** [DNS-OARC/dnsperf#157]
Hi team,

Thanks for providing the awesome tool for DNS performance testing.
Is there any way to specify the real client ip like `dig -subnet` option in this tool? 
I see there is a `-e` option but I have no idea on how to use it to simulate the subnet option in EDNS, any example would be appreciated!

**Comment by jelu** [comment]
You can construct any EDNS0 option with `-e code:hex-payload`, you need to create the hex payload of the ECS ([RFC 7871](https://datatracker.ietf.org/doc/html/rfc7871)) yourself. If you create a script to generate ECS as hex then I can add it for others to use.

**Comment by hdw868** [comment]
> Just added a small script to generate ECS options, have a look at https://github.com/DNS-OARC/dnsperf/tree/develop/contrib/ecs-gen

Thanks, it works well!
