### ISSUE TITLE
Error when running the configure script

### ISSUE THREAD

**Issue by nick22d** [DNS-OARC/dnsperf#177]
Hi team,

I have been struggling to get past the ./configure step as I'm trying to build dnsperf from the GitHub repository. The exact error encountered is the following:

./configure: line 3938: syntax error near unexpected token 'disable-static'
./configure: line 3938: `LT_INIT(disable-static)`

When running echo $? straight after the configure script I get exit status error '2'.

It goes without saying that I have already installed all dependencies. The machine I am working with is ubuntu linux. These are the steps I took prior to getting stuck on the error above:

apt update
apt-get install -y libssl-dev libldns-dev libck-dev libnghttp2-dev autoconf libtool
git clone https://github.com/DNS-OARC/dnsperf.git
cd dnsperf
./autogen.sh
./configure  <-------------WHERE THE PROBLEM OCCURS

I went over the README file 4 times in case there were any other dependencies I had to install but I couldn't see any. Google searching did not help me much either.

Could you please help me with this?

Thanks in advance.

**Comment by jelu** [comment]
You're probably missing libtool.

From README:
> dnsperf requires a couple of libraries beside a normal C compiling environment with autoconf, automake, libtool and pkgconfig.

**Comment by nick22d** [comment]
I actually have libtool installed already along with the other ones mentioned and the issue continues. 

Thanks anyway.

**Comment by jelu** [comment]
Hmm, what distribution and version is this on?

What versions of autoconf, automake and libtool?

Can you attach config.log?

**Comment by jelu** [comment]
If this is still an issue please provide the necessary information and reopen the issue, otherwise I can't help you.

**Comment by thebiss** [comment]
FWIW, I encountered the same error under WSL2, and it was caused by a missing libtool.  

Fixed by re-running the setup process:
```
sudo apt install libtool
./autogen.sh
./configure
```

**Comment by jelu** [comment]
@thebiss that is not the same issue since @nick22d said he already had it installed
