### ISSUE TITLE
support output metrics

### ISSUE THREAD

**Issue by linydquantil** [DNS-OARC/dnsperf#180]
like Flamethrower can generate detailed metrics for each of its concurrent senders. Metrics include send and receive counts, timeouts, min, max and average latency, errors, and the like. The output format is JSON, and is suitable for ingestion into databases such as Elastic for further processing or visualization. See the -o flag.

**Comment by jelu** [comment]
resperf already has this and adding this to dnsperf would essentially mean a total redesign of the software so that's a no-go.
