### ISSUE TITLE
incorrect encoding of qnames with \escapes results in invalid query wire format

### ISSUE THREAD

**Issue by pspacek** [DNS-OARC/dnsperf#183]
Version: 2.7.0

Reproducer:
```
echo '\". A' | dnsperf -v
```

Got
---
dnsperf results:
```
> FORMERR \". A 0.000348
```

Wire format:
```
"\x00\x00\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00\x01\x22\x2e\x00\x00\x01\x00\x01"
```
`\x2e` above is ASCII `.` which is an extra byte - it should not be there.

Expected
------------
dnsperf results:
```
> NXDOMAIN \". A 0.000348
```

Wire format:
```
b'\xb0\xe7\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00\x01\x22\x00\x00\x01\x00\x01'
```

The same happens with other \encoded qnames I tested - `\\. A`, `\123. A`, `\123.xxx A`.

**Comment by jelu** [comment]
Actaully, this is a bug because it should just fail/exit because quoting like that isn't supported at all.

Only `\000` is supported.

**Comment by jelu** [comment]
Nope, I'm wrong :) `\[non-digit]` should be supported and I'm seeing a few bugs in the code now. Will fix tomorrow.

**Comment by pspacek** [comment]
Thanks, much appreciated!

**Comment by jelu** [comment]
Should work better now, let me know how testing goes.
