### ISSUE TITLE
Install or eliminate the libck and libnghttp2 dependencies on Centos 7?

### ISSUE THREAD

**Issue by Quuxplusone** [DNS-OARC/dnsperf#194]
I'm trying to build dnsperf from source on Centos 7.7. This is an AWS machine with very little installed by default:
```
# lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.7.1908 (Core)
Release:	7.7.1908
Codename:	Core
```
Following this repo's README, and following my nose a little, I've come up with these steps:
```
yum install -y git autoconf automake gcc libtool 
yum install -y openssl-devel ldns-devel ck-devel libnghttp2-devel
git clone https://github.com/DNS-OARC/dnsperf.git
cd dnsperf
./autogen.sh
./configure          
make
make install
```
The problem is that two of the packages listed in the README don't exist on Centos 7.7! The `-y` flag (although sensible in general) hides this from the casual copy-paster:
```
[root@foo dnsperf]# yum install openssl-devel ldns-devel ck-devel libnghttp2-devel
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: download.cf.centos.org
 * extras: download.cf.centos.org
 * updates: download.cf.centos.org
Package 1:openssl-devel-1.0.2k-22.el7_9.x86_64 already installed and latest version
Package ldns-devel-1.6.16-10.el7.x86_64 already installed and latest version
No package ck-devel available.
No package libnghttp2-devel available.
Nothing to do
```
And then when you get four steps further along in the step-by-step above:
```
[root@foo dnsperf]# ./configure
checking for libssl... yes
checking for libcrypto... yes
checking for TLS_method in -lssl... no
checking for ck... no
checking ck_ring.h usability... no
checking ck_ring.h presence... no
checking for ck_ring.h... no
configure: error: libck headers not found
```

My question is: How can I get these packages `libck` and `libnghttp2` on Centos 7.7? Or, how can I convince dnsperf to build without them?

FWIW, I'm really interested only in the `resperf` program; I don't need the `dnsperf` program itself.

[This other issue](https://github.com/DNS-OARC/dnsperf/issues/155#issuecomment-826643306) seems related but I can't figure out what the recommended action is.

**Comment by Quuxplusone** [comment]
It's possible that the recommended course of action will be "install those libraries from source too." Anyway, that seems at least to be a _possible_ approach. For posterity, here's what I've done on my Centos machine (yoloing everything as `root` because it's an AWS box and I'm just gonna throw it away in a minute):

    sudo -i
    yum install -y git autoconf automake gcc libtool
    yum install -y openssl-devel ldns-devel ck-devel libnghttp2-devel
    git clone https://github.com/concurrencykit/ck
    pushd ck
      ./configure
      make install
      popd
    curl -L -O https://github.com/nghttp2/nghttp2/releases/download/v1.46.0/nghttp2-1.46.0.tar.gz
    tar zxvf nghttp2-1.46.0.tar.gz
    pushd nghttp2-1.46.0
      ./configure
      make install
      cp lib/libnghttp2.pc /usr/share/pkgconfig/
      popd
    git clone https://github.com/DNS-OARC/dnsperf
    pushd dnsperf
      ./autogen.sh
      ./configure
      make install
      popd
    exit

Now `dnsperf` and `resperf` exist in `/usr/local/bin` (which is part of the non-root user's PATH).

**Comment by jelu** [comment]
> The problem is that two of the packages listed in the README don't exist on Centos 7.7!

Did you enable EPEL?

**Comment by Quuxplusone** [comment]
> Did you enable EPEL?

Aha! After some further googling (for "centos enable epel"), my new recipe is:
```
sudo -i
yum install -y epel-release
yum install -y git autoconf automake gcc libtool
yum install -y openssl-devel ldns-devel ck-devel libnghttp2-devel
git clone https://github.com/DNS-OARC/dnsperf
pushd dnsperf
  ./autogen.sh
  ./configure
  make install
  popd
exit
```

Assuming this sounds right, then I think you can close this issue; thanks!

**Comment by jelu** [comment]
We also have packages if you don't want to compile yourself: https://dev.dns-oarc.net/packages/
