### ISSUE TITLE
new feature: at most N queries over a single TCP connection

### ISSUE THREAD

**Issue by pspacek** [DNS-OARC/dnsperf#195]
It would be awesome if dnsperf had a mode where each connection is used at most <N> times, where N is user-specified value. It would allow to exercise connection open/close code paths more heavily than the current "optimal" mechanism which pipelines everything.

Bonus points if the parameter allows `0`, i.e. open a new connection and close it right away without sending a query. Of course it's dumb, but I have a use-case where one dnsperf/client instance hammers the server with TCP open/close and another instance tries to get answers to useful DNS queries.

Thank you for considering this.

**Comment by jelu** [comment]
While I think it wouldn't be that hard to add a feature like this, it will have consequences that you might not have thought about.

For example, closing and reopening a connection will drop all in-flight queries and setting this value to 1 or less will saturate the TCP ports within seconds.

I could start a branch and try to add this feature but only if your willing to put time into testing it and help tweaking it.

**Comment by jelu** [comment]
FTR: this is being developed in https://github.com/jelu/dnsperf/tree/num-queries-per-conn

**Comment by jelu** [comment]
TODO:
- "Timeout" waiting for responses
