### ISSUE TITLE
DNSPerf 2.11.1 Homebrew MacOS Ventura

### ISSUE THREAD

**Issue by RobertPaolucci-CUJO** [DNS-OARC/dnsperf#234]
dnsperf-2.11.1 on macos ventura using homebrew

doh-uri extended option not working:

dnsperf -m doh -s blahblah.com -O doh-uri=https://blahblah.com/dns-query

DNS Performance Testing Tool
Version 2.11.1

invalid long option: doh-uri=https://blahblah.com/dns-query

Cannot seem to get it to take a uri, have tried many iterations of the syntax

robertpaolucci@CNMUS0022 dnsperf-2.11.1 % dnsperf -H                                                                                                                          
DNS Performance Testing Tool
Version 2.11.1

Usage: dnsperf ... -O <name>[=<value>] ...

Available long options:
  latency-histogram: collect and print detailed latency histograms
  verbose-interval-stats: print detailed statistics for each stats_interval
  num-queries-per-conn=<queries>: Number of queries to send per connection
  suppress=<message[,message,...]>: suppress messages/warnings, see man-page for list of message types
  doh-method=<doh_method>: the HTTP method to use for DNS-over-HTTPS: GET or POST (default: GET)
  doh-uri=<doh_uri>: the URI to use for DNS-over-HTTPS (default: https://localhost/dns-query)

**Comment by jelu** [comment]
It's option=value

Try:

-O doh-uri=https://blahblah.com/dns-query

**Comment by jelu** [comment]
Sorry, didn't see the edit in my email. Thanks for the report, will fix as soon as I can.

**Comment by jelu** [comment]
@RobertPaolucci-CUJO can you compile develop branch and test?
