### ISSUE TITLE
DoH: seg fault when issuing qps < clients/connections and low num-queries-per-conn (1 or 2)

### ISSUE THREAD

**Issue by kgillis2000** [DNS-OARC/dnsperf#241]
Attempting to use dnsperf 2.11.2 to characterize performance on a production dns server (CacheServe) using DoH requests.  However, running into seg faults when using a qps that is lower than the total number of connections, as well as controlling the number of queries per connection.

Ex. dnsperf -m doh -s <dns server> -d <test file> -q 140 -l 300 -Q 15 -c 60 -T 4 -W -O num-queries-per-conn=1 -O doh-method=GET -S 1

Can avoid the seg fault by reducing the thread count to 1 (-T 1).  Attaching back trace of the above command line.  Error occurs for both POST and GET requests.

What's interesting is that was not able to repro issue on dns.google.

dnsperf -s 8.8.8.8 -l 120 -m doh -T 4 -c 100 -O num-queries-per-conn=1 -d <test file> -Q 25 -S 1 -O doh-method=GET -t 10

[DoH_GET_60client_15qps_1qpc.txt](https://github.com/DNS-OARC/dnsperf/files/11499334/DoH_GET_60client_15qps_1qpc.txt)

**Comment by jelu** [comment]
Are you using the pre-release version with the DoH fix?

The fix was not just for POST.

**Comment by kgillis2000** [comment]
I just tested on the cloud instance that was used to debug https://github.com/DNS-OARC/dnsperf/issues/238, and do not see the error condition so assume it's running with the pre-release version.  That would be great if the previous fix addresses this issue.  Thought it might be a different issue based on the signature of the backtrace.  Thanks!

**Comment by jelu** [comment]
The bug is pretty wide, so use the pre-release until I get time to do a release.

**Comment by kgillis2000** [comment]
Thanks.  What is the best way to obtain a pre-release build?

**Comment by kgillis2000** [comment]
Thanks!  Mike came across this site the other day.  I installed the rpm and it's working fine.
