### ISSUE TITLE
[DoT] No timeout?

### ISSUE THREAD

**Issue by bortzmeyer** [DNS-OARC/dnsperf#247]
When  using `-m dot` and directing dnsperf to the port of an ordinary DNS server using plain TCP, the TLS negotiation fails (obviously) but dnsperf never times out, never stops. If I interrupt it with Control-C, it displays:

```
DNS Performance Testing Tool
Version 2.13.0

[Status] Command line: dnsperf -n 250 -c 1 -s 192.0.2.1 -p 3553 -d my.data -m dot
[Status] Sending queries (to 192.0.2.1:3553)
[Status] Started at: Fri Jul 21 11:27:24 2023
[Status] Stopping after 250 runs through file
^C[Status] Testing complete (interruption)

Statistics:

  Queries sent:         0
  Queries completed:    0 (0.00%)
  Queries lost:         0 (0.00%)

  Response codes:       
  Average packet size:  request 0, response 0
  Run time (s):         6215.971513
  Queries per second:   0.000000

  Average Latency (s):  0.000000 (min 0.000000, max 0.000000)

Connection Statistics:

  Reconnections:        3105 (0.00% of 0 connections)

  Average Latency (s):  0.000000 (min 0.000000, max 0.000000)

```

**Comment by jelu** [comment]
It can't timeout because it hasn't sent anything yet.

You should use `-l <seconds>` instead of `-n` if you want it to stop after a certain time.

**Comment by bortzmeyer** [comment]
IMHO, dnsperf should timeout when it cannot establish a TLS session (or a TCP connection, they have the same behaviour).

**Comment by jelu** [comment]
Sure that's your opinion, but there are equal or more people that expect this behavior of retrying for the full duration of how long they specified it should run.

Your more then welcome to submit a PR that adds an extended option to change the default behavior.
