### ISSUE TITLE
TCP queries larger than 4 KiB are truncated

### ISSUE THREAD

**Issue by pspacek** [DNS-OARC/dnsperf#251]
Version affected: 2.13.0

Messages larger than 4 KiB (`TCP_SEND_BUF_SIZE - 2`) are not supported by dnsperf. Larger messages are truncated and the first part of the message is still _sent_ to the TCP connection with message preambule saying it's size is `TCP_SEND_BUF_SIZE - 2`.

This truncation breaks the message and causes parsing errors on the remote end.

I can see two ways out:
- do not send too large messages at all
- support messages up to 64 KiB

Personally I would go for 64 KiB because it removes once nasty corner case, and I just have use-case for that for testing large UPDATE. This is implemented in https://github.com/DNS-OARC/dnsperf/pull/250.

**Comment by jelu** [comment]
Did you test #250 ?

I don't think the receive and send buffer for TCP has nothing to do with how large DNS messages are allowed.
