### ISSUE TITLE
"Reconnection" count is confusing

### ISSUE THREAD

**Issue by pspacek** [DNS-OARC/dnsperf#254]
I think term "reconnection" in connection statistics is confusing. It would be better to explicitly split successful and failed connection attempts. Here's an extreme example:

Version: 2.13.1

Reproducer:
1. start dnsperf while server (remote end) is not listening yet
```console
dnsperf -s ::1 -m tcp
```
2. run server, e.g. `named -g -c /dev/null`

3. stop dnsperf with SIGINT
```
Connection Statistics:

  Reconnections:        80737 (4036850.00% of 2 connections)
```

I find this very confusing. What about this output format?

```
Connection Statistics:

  Connection attempts:        80737 (2 successful, 0.002477 %)
```

**Comment by jelu** [comment]
Sure, PR it!

**Comment by pspacek** [comment]
Hmm, I thought it's just format string change but it's not. `num_conn_reconnect` does not count initial attempts. I will rename it and make it count all attempts.
