### ISSUE TITLE
parameter -t doesn't work 

### ISSUE THREAD

**Issue by sarahsiyufine** [DNS-OARC/dnsperf#262]
Thank you for your magnificant tool!
When I encounter queries timed out, I try to set "the timeout for query completion in seconds" with longer time, like 10, 20, 100. but the queries still time out. And the queries max latency is still within 5 seconds.

**Comment by jelu** [comment]
@sarahsiyufine please provide version, OS/dist and full output of running `dnsperf`

**Comment by sarahsiyufine** [comment]
it's version 2.14.0., ubuntu18server
it works now and then.
sometimes it works:
![图片](https://github.com/DNS-OARC/dnsperf/assets/56600623/20240536-99cd-4921-bce6-5f0042411275)
![图片](https://github.com/DNS-OARC/dnsperf/assets/56600623/e83d7479-979d-42ba-8124-c555c6376ab4)
sometimes it doesn't:
![图片](https://github.com/DNS-OARC/dnsperf/assets/56600623/37a85412-b1f7-4f1c-bb81-65c2aa360821)
![图片](https://github.com/DNS-OARC/dnsperf/assets/56600623/7972ff11-9ed1-46be-a650-0fa7ecb44a25)
thank u for your patience.

**Comment by jelu** [comment]
I can't see any issue here, timeout is per query - not for total run time. And timed out queries are not included in latency.

```
$ time src/dnsperf -d ../src/test/datafile -p 5353 -t 1 -n 2 -c 1 -Q 1 -v
DNS Performance Testing Tool
Version 2.14.0

[Status] Command line: dnsperf -d ../src/test/datafile -p 5353 -t 1 -n 2 -c 1 -Q 1 -v
[Status] Sending queries (to 127.0.0.1:5353)
[Status] Started at: Mon Mar 18 08:50:45 2024
[Status] Stopping after 2 runs through file
> T google.com A
> T google.com AAAA
> T google.com A
> T google.com AAAA
[Status] Testing complete (end of file)

Statistics:

  Queries sent:         4
  Queries completed:    0 (0.00%)
  Queries lost:         4 (100.00%)

  Response codes:       
  Average packet size:  request 28, response 0
  Run time (s):         4.000234
  Queries per second:   0.000000

  Average Latency (s):  0.000000 (min 0.000000, max 0.000000)


real	0m4.021s
user	0m0.007s
sys	0m0.012s
```

What are you expecting?

**Comment by sarahsiyufine** [comment]
i understand. thank you for your explanation.

**Comment by jelu** [comment]
@sarahsiyufine `dnsperf` has many options, if you can explain your testing scenario and what you're expecting it to do then I can see if there is an option for you to use to get to that.
