### ISSUE TITLE
documentation lost (?)

### ISSUE THREAD

**Issue by vcunat** [DNS-OARC/dnsperf#27]
The "original" [version 2.1.0.0](ftp://ftp.nominum.com/pub/nominum/dnsperf/2.1.0.0/dnsperf-src-2.1.0.0-1.tar.gz) had quite nice PDFs in it.  Have we lost those?  I've never seen any sources for those PDFs, so I'm afraid it's possible we won't be able to get their sources anymore :cry:

**Comment by vcunat** [comment]
:thinking: maybe I was too fast and they don't really hold much value in addition to what we have in the man-pages.  I'll try to revisit this later (but feel free to dig yourself).

**Comment by jelu** [comment]
I did find these when I copied the old site: [dnsperf.pdf](https://www.dns-oarc.net/files/dnsperf/2.0.0.0/dnsperf.pdf) [resperf.pdf](https://www.dns-oarc.net/files/dnsperf/2.0.0.0/resperf.pdf).

There were none for 2.1.0.0 and I don't have the document they where rendered from.

I'm not keen on maintaining PDFs, easier to make man-pages.

**Comment by jelu** [comment]
Added links to the PDF's on https://www.dns-oarc.net/tools/dnsperf
