### ISSUE TITLE
Calculation error in per_thread() ?

### ISSUE THREAD

**Issue by raybellis** [DNS-OARC/dnsperf#3]
I believe there's an error in the usage of the `offset` parameter in the `per_thread()` function?

It's giving me unexpected results, where for example if I specify `-T 6 -c 24` I would expect to get exactly four sockets per thread, but I'm actually getting the sequence (5, 5, 5, 5, 4, 4) making a total of 28 clients created instead of the specified 24.

**Comment by jelu** [comment]
Merge onto develop in #14
