### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by jiangby123** [DNS-OARC/dnsperf#32]
# ./autogen.sh
./autogen.sh: line 19: autoreconf: command not found

Dependencies are already installed
My thing centos system

**Comment by jelu** [comment]
Did you also?

https://github.com/DNS-OARC/dnsperf/blob/develop/README.md#dependencies:
> `dnsperf` requires a couple of libraries beside a normal C compiling
environment with autoconf, automake, libtool.

**Comment by jiangby123** [comment]
> 你也是吗？
> 
> https://github.com/DNS-OARC/dnsperf/blob/develop/README.md#dependencies：
> 
> > `dnsperf`在
> > autoconf，automake，libtool 的普通C编译环境旁边需要几个库。

This simply cannot be installed

**Comment by jelu** [comment]
What do you mean?

What errors are you getting?

Maybe you should use our packages instead https://copr.fedorainfracloud.org/coprs/g/dnsoarc/dnsperf/

**Comment by jelu** [comment]
I assume that your using the packages now.

If your not, have installed the required compiling environment and still get issues then your can reopen this issue and include output of the errors.
