### ISSUE TITLE
undefined reference to `isc_hmacmd5_init'

### ISSUE THREAD

**Issue by beckhamaaa** [DNS-OARC/dnsperf#33]
i have several question about dnsperf, when i build from sources, i suffer from "undefined reference to `isc_hmacmd5_init'" , how can i next? i know the question about so。

**Comment by vcunat** [comment]
Perhaps https://github.com/DNS-OARC/dnsperf/issues/22  (at a very quick glance)

**Comment by vcunat** [comment]
In any case I'd suggest you build dnsperf against bind 9.12.x for now.  That seems to work fine for me.

**Comment by jelu** [comment]
@vcunat Hmm, don't think so, #22 is about the new interface and I added compat for old.

@beckhamaaa 
- What version / branch / commit are you building?
- What system are you building it on?
- What steps did you do to build it?
- Can you paste full `configure` and `make` logs?

**Comment by jelu** [comment]
@beckhamaaa Please don't comment this issue in other issues. If you can answer my questions we can surely get to the problem and get it fixed.

**Comment by beckhamaaa** [comment]
ok, sorry, there is my bind version: https://www.isc.org/downloads/file/bind-9-14-2/
there is my configure options:
./configure --with-libtool --disable-linux-caps --with-dlz-postgres --with-dlz-mysql --enable-querytrace --with-openssl=/usr/local

**Comment by vcunat** [comment]
Actually dnsperf 2.2.0 and 2.2.1 build fine against bind 9.14.2 for me.

**Comment by beckhamaaa** [comment]
@ my operational system is ubuntu 16.04 server

**Comment by beckhamaaa** [comment]
@jelu  my operational system is ubuntu16.04 server

**Comment by jelu** [comment]
@beckhamaaa Please, **all** commands for all dependencies and how you compile dnsperf, also **full** output from `configure` and `make`

**Comment by beckhamaaa** [comment]
@jelu 
please fix the bug in the offical version:
1. /usr/bin/ld: dnsperf.o: undefined reference to symbol 'sqrt@@GLIBC_2.2.5'
i modify Makefile "LIBS = "-lnsl -lm"", so can build success.
2. i build success from bind-9.12

there is the build process in bind-9.14.2:
1. # ./autogen.sh 
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:26: installing './compile'
configure.ac:20: installing './missing'
src/Makefile.am: installing './depcomp'

2. ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes 
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes 
checking whether make supports nested variables... yes 
checking for gcc... gcc 
checking whether the C compiler works... yes 
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes 
checking whether gcc accepts -g... yes 
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes 
checking for style of include used by make... GNU 
checking dependency style of gcc... gcc3
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for inline... inline
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking whether gcc is Clang... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking for socket in -lsocket... no
checking for inet_ntoa in -lnsl... yes
checking for BIND 9 libraries... checking for isc-config.sh... /usr/local/bin/isc-config.sh
checking isc/hmacmd5.h usability... no
checking isc/hmacmd5.h presence... yes
checking for isc/hmacmd5.h... no
checking isc/hmacsha.h usability... no
checking isc/hmacsha.h presence... yes
checking for isc/hmacsha.h... no
checking for socklen_t... yes
checking for sa_len... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating src/config.h
config.status: src/config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands

root@ubuntu-1:/usr/local/dnsperf# make
Making all in src
make[1]: Entering directory '/usr/local/dnsperf/src'
make  all-recursive
make[2]: Entering directory '/usr/local/dnsperf/src'
make[3]: Entering directory '/usr/local/dnsperf/src'
/bin/bash ../libtool  --tag=CC   --mode=link gcc -I. -I.. -pthread -g -O2 -I/usr/local/include  -L/usr/local/lib -lbind9 -ldns -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lisccfg -lisc -L/usr/local/lib -lcrypto -ldl -lz -llmdb -lxml2 -o dnsperf datafile.o dns.o log.o net.o opt.o os.o dnsperf.o   -lnsl 
libtool: link: gcc -I. -I.. -pthread -g -O2 -I/usr/local/include -o dnsperf datafile.o dns.o log.o net.o opt.o os.o dnsperf.o  -L/usr/local/lib /usr/local/lib/libbind9.so /usr/local/lib/libdns.so -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err /usr/local/lib/libisccfg.so /usr/local/lib/libisc.so -lcrypto -ldl -lz -llmdb -lxml2 -lnsl -pthread
/usr/bin/ld: dnsperf.o: undefined reference to symbol 'sqrt@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:525: recipe for target 'dnsperf' failed
make[3]: *** [dnsperf] Error 1
make[3]: Leaving directory '/usr/local/dnsperf/src'
Makefile:660: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/usr/local/dnsperf/src'
Makefile:426: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/local/dnsperf/src'
Makefile:460: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by beckhamaaa** [comment]
@jelu 
please fix the bug in the offical version:
1. /usr/bin/ld: dnsperf.o: undefined reference to symbol 'sqrt@@GLIBC_2.2.5'
i modify Makefile "LIBS = "-lnsl -lm"", so can build success.
2. i build success from bind-9.12

there is the build process in bind-9.14.2:
1. # ./autogen.sh 
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:26: installing './compile'
configure.ac:20: installing './missing'
src/Makefile.am: installing './depcomp'

2. ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes 
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes 
checking whether make supports nested variables... yes 
checking for gcc... gcc 
checking whether the C compiler works... yes 
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes 
checking whether gcc accepts -g... yes 
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes 
checking for style of include used by make... GNU 
checking dependency style of gcc... gcc3
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for inline... inline
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking whether gcc is Clang... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking for socket in -lsocket... no
checking for inet_ntoa in -lnsl... yes
checking for BIND 9 libraries... checking for isc-config.sh... /usr/local/bin/isc-config.sh
checking isc/hmacmd5.h usability... no
checking isc/hmacmd5.h presence... yes
checking for isc/hmacmd5.h... no
checking isc/hmacsha.h usability... no
checking isc/hmacsha.h presence... yes
checking for isc/hmacsha.h... no
checking for socklen_t... yes
checking for sa_len... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating src/config.h
config.status: src/config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands

# make
Making all in src
make[1]: Entering directory '/usr/local/dnsperf/src'
make  all-recursive
make[2]: Entering directory '/usr/local/dnsperf/src'
make[3]: Entering directory '/usr/local/dnsperf/src'
/bin/bash ../libtool  --tag=CC   --mode=link gcc -I. -I.. -pthread -g -O2 -I/usr/local/include  -L/usr/local/lib -lbind9 -ldns -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lisccfg -lisc -L/usr/local/lib -lcrypto -ldl -lz -llmdb -lxml2 -o dnsperf datafile.o dns.o log.o net.o opt.o os.o dnsperf.o   -lnsl 
libtool: link: gcc -I. -I.. -pthread -g -O2 -I/usr/local/include -o dnsperf datafile.o dns.o log.o net.o opt.o os.o dnsperf.o  -L/usr/local/lib /usr/local/lib/libbind9.so /usr/local/lib/libdns.so -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err /usr/local/lib/libisccfg.so /usr/local/lib/libisc.so -lcrypto -ldl -lz -llmdb -lxml2 -lnsl -pthread
/usr/bin/ld: dnsperf.o: undefined reference to symbol 'sqrt@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:525: recipe for target 'dnsperf' failed
make[3]: *** [dnsperf] Error 1
make[3]: Leaving directory '/usr/local/dnsperf/src'
Makefile:660: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/usr/local/dnsperf/src'
Makefile:426: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/local/dnsperf/src'
Makefile:460: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by beckhamaaa** [comment]
@jelu 
please fix the bug in the offical version:
1. /usr/bin/ld: dnsperf.o: undefined reference to symbol 'sqrt@@GLIBC_2.2.5'
i modify Makefile "LIBS = "-lnsl -lm"", so can build success.
2. i build success from bind-9.12

there is the build process in bind-9.14.2:
1. # ./autogen.sh 
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:26: installing './compile'
configure.ac:20: installing './missing'
src/Makefile.am: installing './depcomp'

2. ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes 
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes 
checking whether make supports nested variables... yes 
checking for gcc... gcc 
checking whether the C compiler works... yes 
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes 
checking whether gcc accepts -g... yes 
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes 
checking for style of include used by make... GNU 
checking dependency style of gcc... gcc3
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for inline... inline
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking whether gcc is Clang... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking for socket in -lsocket... no
checking for inet_ntoa in -lnsl... yes
checking for BIND 9 libraries... checking for isc-config.sh... /usr/local/bin/isc-config.sh
checking isc/hmacmd5.h usability... no
checking isc/hmacmd5.h presence... yes
checking for isc/hmacmd5.h... no
checking isc/hmacsha.h usability... no
checking isc/hmacsha.h presence... yes
checking for isc/hmacsha.h... no
checking for socklen_t... yes
checking for sa_len... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating src/config.h
config.status: src/config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands

3. # make
Making all in src
make[1]: Entering directory '/usr/local/dnsperf/src'
make  all-recursive
make[2]: Entering directory '/usr/local/dnsperf/src'
make[3]: Entering directory '/usr/local/dnsperf/src'
/bin/bash ../libtool  --tag=CC   --mode=link gcc -I. -I.. -pthread -g -O2 -I/usr/local/include  -L/usr/local/lib -lbind9 -ldns -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lisccfg -lisc -L/usr/local/lib -lcrypto -ldl -lz -llmdb -lxml2 -o dnsperf datafile.o dns.o log.o net.o opt.o os.o dnsperf.o   -lnsl 
libtool: link: gcc -I. -I.. -pthread -g -O2 -I/usr/local/include -o dnsperf datafile.o dns.o log.o net.o opt.o os.o dnsperf.o  -L/usr/local/lib /usr/local/lib/libbind9.so /usr/local/lib/libdns.so -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err /usr/local/lib/libisccfg.so /usr/local/lib/libisc.so -lcrypto -ldl -lz -llmdb -lxml2 -lnsl -pthread
/usr/bin/ld: dnsperf.o: undefined reference to symbol 'sqrt@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:525: recipe for target 'dnsperf' failed
make[3]: *** [dnsperf] Error 1
make[3]: Leaving directory '/usr/local/dnsperf/src'
Makefile:660: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/usr/local/dnsperf/src'
Makefile:426: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/local/dnsperf/src'
Makefile:460: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by jelu** [comment]
@beckhamaaa Please use [MarkDown](https://guides.github.com/features/mastering-markdown/) when adding output.

How did you install bind-9.14.2 ?

**Comment by beckhamaaa** [comment]
@jelu  ok, 
i install by configure and make

**Comment by jelu** [comment]
I don't really know why you need to build against bind 9.14.2, here is my test on Ubuntu 16.04 and it works fine if you use [the instructions in the README](https://github.com/DNS-OARC/dnsperf/blob/develop/README.md#dependencies):
```
$ docker run -it --rm ubuntu:16.04
$ apt-get update
$ apt-get -y dist-upgrade
$ apt-get -y install build-essential autoconf automake libtool git
$ git clone https://github.com/DNS-OARC/dnsperf.git
$ cd dnsperf/
$ cat README.md
$ apt-get install -y libbind-dev libkrb5-dev libssl-dev libcap-dev libxml2-dev libjson-c-dev libgeoip-dev
$ sh autogen.sh 
$ ./configure
$ make
$ src/dnsperf -h
DNS Performance Testing Tool
Version 2.2.1
...
```

You can also use our [packages](https://dev.dns-oarc.net/packages/) for Ubuntu:
```
$ docker run -it --rm ubuntu:16.04
$ apt-get -y install software-properties-common
$ add-apt-repository -y ppa:isc/bind-esv
$ add-apt-repository -y ppa:dns-oarc/dnsperf
$ apt-get update
$ apt-get -y install dnsperf
$ dnsperf -h
DNS Performance Testing Tool
Version 2.2.1
...
```
NOTE: Only reason Bind ESV repository is needed is because of build issues on LaunchPad, it is usually not needed if your building it yourself.


If you have more problems you can reopen this issue or create a new but **I really need full instructions on how you did it so that I can replicate it**, if I can't replicate the problem I can't fix it!

**Comment by beckhamaaa** [comment]
@jelu  okay, i try it,  thanks a lot!
