### ISSUE TITLE
Error: ran out of query data

### ISSUE THREAD

**Issue by beckhamaaa** [DNS-OARC/dnsperf#35]
i suffer from the question about when i use resperf to test DNS performmance.
**there is the console:**
**$ resperf -d datafile.txt -s xxx**
DNS Resolution Performance Testing Tool
Version 2.2.1

[Status] Command line: resperf -d a.txt -s xxx
[Status] Sending
Error: ran out of query data

**there is my datafile:**
dns1.ikang.com.      A
s-static.ak.fbcdn.net.  A
lachicabionica.com.     A
www.mediafire.com.      A
can you help me, thanks！

**Comment by jelu** [comment]
Use `-l` or `-n` also, read about all options in `man dnsperf`.
