### ISSUE TITLE
Very slow TCP support

### ISSUE THREAD

**Issue by nombwelling** [DNS-OARC/dnsperf#43]
I'm attempting to use the new TCP support in 2.30 against Akamai/Nominum Vantio CacheServe.  The server configuration is trivial, and the dnsperf input file is a single query, which will be answered out of the server's cache.  I'm sending queries between 2 reasonably fast machines running CentOS 6.5 in the same lab.

I'm running this command:

dnsperf -s platform-perf-vantio-1 -p 12347 -d in -l10 -c2 -m tcp

and seeing results like this:

  Queries sent:         215420
  Queries completed:    215420 (100.00%)
  Queries lost:         0 (0.00%)

  Response codes:       NOERROR 215420 (100.00%)
  Average packet size:  request 29, response 61
  Run time (s):         10.064001
  Queries per second:   21405.005822

  Average Latency (s):  0.004335 (min 0.000075, max 0.080095)
  Latency StdDev (s):   0.008782

(for the record, when using UDP instead of TCP, I'm seeing about 250000 queries per second).

When I try using 2.2.1 with the pull request in #34 (and one minor bug fix, to fix a problem that showed up on Linux and not macOS), and using "-z" instead of "-m tcp", I'm seeing this:

  Queries sent:         2476115
  Queries completed:    2476115 (100.00%)
  Queries lost:         0 (0.00%)

  Response codes:       NOERROR 2476115 (100.00%)
  Average packet size:  request 31, response 61
  Run time (s):         10.007593
  Queries per second:   247423.631237

That's 11.5x faster.

As another comparison point, if I use dnsperf from https://github.com/Sinodun/dnsperf-tcp, also using -z, I see this:

  Queries sent:         1932941
  Queries completed:    1932941 (100.00%)
  Queries lost:         0 (0.00%)

  Response codes:       NOERROR 1932941 (100.00%)
  Average packet size:  request 31, response 61
  Run time (s):         10.039865
  Queries per second:   192526.592738

  TCP connections:      2
  Ave Queries per conn: 966471
  TCP HS time per client (s):          0.000000  (0.00%)
  TLS HS time per client (s):          0.000000  (0.00%)
  Total HS time per client (s):        0.000000  (0.00%)
  TCP HS time per connection (s):      0.000000
  TLS HS time per connection (s):      0.000000
  Total HS time per connection (s):    0.000000
  Adjusted Queries/s:   192526.592738

That's 9x faster.

I'm not sure what the code in 2.3.0 is doing (it's pretty opaque and not commented), but I don't understand how it can be so much slower, or why the pull request was rejected.

**Comment by jelu** [comment]
When I tested this against my local resolver I got 40 KQPS with your TCP code and 70 KQPS with mine (as reference got 95 KQPS UDP), that's why I went ahead with my branch.

Would it be possible for me to get access to the servers?

**Comment by nombwelling** [comment]
Not easily, it’s behind corporate firewalls.

I fixed one bug yesterday in the fork I created for the pull request; without it, it worked well for a few seconds, and then started incorrectly triggering the short response detection and queries started timing out.  If you were seeing that, it could explain the discrepancy.  It’s also possible that there is some other issue that shows up in longer runs, which I can try to look for.

**Comment by jelu** [comment]
Can you post a link directly to the commit so I can look at it?

>

**Comment by nombwelling** [comment]
The bug I fixed yesterday is https://github.com/nombwelling/dnsperf/commit/cc347f7ba2f72b5d1ac1867da462a5b66563ba8b

**Comment by jelu** [comment]
Just did some more tests using a local NSD, both branches did ~160Kqps for UDP but my branch did 82 Kqps TCP while yours did 57 Kqps.

If I can't replicate the scenario your describing or can't get access to it then it's very hard for me to try and fix it.

Current develop branch:
```
$ src/dnsperf -d test -s localhost -p 5353 -S 1 -c 2 -l 10 -m tcp
DNS Performance Testing Tool
Version 2.3.0

[Status] Command line: dnsperf -d test -s localhost -p 5353 -S 1 -c 2 -l 10 -m tcp
[Status] Sending queries (to 127.0.0.1)
[Status] Started at: Mon Jul 22 09:54:22 2019
[Status] Stopping after 10.000000 seconds
1563782063.913385: 80394.781532
1563782064.914552: 77094.031266
1563782065.915383: 84569.722561
1563782066.916414: 84041.353365
1563782067.917449: 84552.488175
1563782068.918478: 82698.902829
1563782069.919393: 84786.420425
1563782070.920446: 83975.573721
1563782071.921481: 84808.223489
[Status] Testing complete (time limit)

Statistics:

  Queries sent:         831508
  Queries completed:    831508 (100.00%)
  Queries lost:         0 (0.00%)

  Response codes:       NOERROR 831508 (100.00%)
  Average packet size:  request 29, response 140
  Run time (s):         10.043158
  Queries per second:   82793.479899

  Average Latency (s):  0.001001 (min 0.000021, max 0.043656)
  Latency StdDev (s):   0.000349
```

Your branch:
```
$ src/dnsperf -d test -s localhost -p 5353 -S 1 -c 2 -l 10 -z
DNS Performance Testing Tool
Version 2.2.1

[Status] Command line: dnsperf -d test -s localhost -p 5353 -S 1 -c 2 -l 10 -z
[Status] Sending queries (to 127.0.0.1)
[Status] Started at: Mon Jul 22 09:56:48 2019
[Status] Stopping after 10.000000 seconds
1563782209.991392: 54604.225844
1563782210.991732: 57085.590899
1563782211.993112: 56599.892149
1563782212.994189: 57070.535034
1563782213.995223: 57712.325455
1563782214.995401: 60211.282392
1563782215.996436: 57917.055847
1563782216.997465: 58966.323653
1563782217.998503: 58039.754735
[Status] Testing complete (time limit)

Statistics:

  Queries sent:         577496
  Queries completed:    577496 (100.00%)
  Queries lost:         0 (0.00%)

  Response codes:       NOERROR 577496 (100.00%)
  Average packet size:  request 31, response 140
  Run time (s):         10.044212
  Queries per second:   57495.401332

  Average Latency (s):  0.001683 (min 0.000026, max 0.044669)
  Latency StdDev (s):   0.000554
```

**Comment by jelu** [comment]
Sinodun's TCP branch on the same setup:
```
$ ./dnsperf -d test -s localhost -p 5353 -S 1 -c 2 -l 10 -z
DNS Performance Testing Tool
Nominum Version 2.1.0.0

[Status] Command line: dnsperf -d test -s localhost -p 5353 -S 1 -c 2 -l 10 -z
[Status] Sending queries (to 127.0.0.1) over TCP 
[Status] Started at: Mon Jul 22 10:02:26 2019
[Status] Stopping after 10.000000 seconds
1563782547.091385: 57216.922232
1563782548.092415: 61071.096770
1563782549.093473: 58865.720068
1563782550.094507: 58912.084904
1563782551.095392: 60061.845267
1563782552.096428: 59638.214809
1563782553.097396: 60865.082600
1563782554.098431: 57863.111679
1563782555.099395: 57560.511667
[Status] Testing complete (time limit)

Statistics:

  Queries sent:         592987
  Queries completed:    592987 (100.00%)
  Queries lost:         0 (0.00%)

  Response codes:       NOERROR 592987 (100.00%)
  Average packet size:  request 31, response 140
  Run time (s):         10.041165
  Queries per second:   59055.597632

  TCP connections:      2
  Ave Queries per conn: 296494
  TCP HS time per client (s):          0.000000  (0.00%)
  TLS HS time per client (s):          0.000000  (0.00%)
  Total HS time per client (s):        0.000000  (0.00%)
  TCP HS time per connection (s):      0.000000
  TLS HS time per connection (s):      0.000000
  Total HS time per connection (s):    0.000000
  Adjusted Queries/s:   59055.597632


  Average RTT (s):      0.001633 (min 0.000027, max 0.041227)
  RTT StdDev (s):       0.000555
```

**Comment by jelu** [comment]
Just found an issue with the receive buffer code (#44), it might explain your results compared to mine since your most likely hitting buffering then I am.

Can you test the latest develop branch again?

**Comment by nombwelling** [comment]
I did 5 more runs with the new develop branch, and I’m seeing:

  Queries per second:   20142.557635
  Queries per second:   49357.139406
  Queries per second:   29039.707329
  Queries per second:   33376.284135
  Queries per second:   29563.013271


and 1 more with my branch, just to make sure nothing was different today.

  Queries per second:   275898.108090

Out of curiosity, I tried removing the code calling poll() on the socket, prefaced by:

// Poll TCP sock to not choke it with recv(), increased throughput by ~50%

and started seeing much better performance:

  Queries per second:   255360.865520
  Queries per second:   272668.846235
  Queries per second:   273815.560604

I still think that there’s a bit more performance compared to my code lost due to the extra memcpy/memmove, but that poll call seems to be the main issue.

I don’t have a good explanation for this, but I will mention that when developing dnsperf over the last 10 years or so, I’ve consistently found that testing over loopback yields vastly different results than testing over a real network.  All of that testing would have been UDP and not TCP, but I wouldn’t be surprised if TCP had the same properties.

**Comment by jelu** [comment]
Ah, I think this is related to CentOS 6.5 also, that runs quite an old kernel and a lot of improvements have been done to `poll()` and likewise.

I'm not keen to just remove it since it actually gives gains in other scenarios.

Will give this some thought.

**Comment by nombwelling** [comment]
That’s certainly possible, but I think the fundamental issue is performance, and (at least in my opinion) the code should be optimizing for the case where performance (both of dnsperf and the server being tested) is highest.

If the socket is readable, the poll() call will return immediately, and the read() will succeed.  The poll() call provides no value in the case.

If the socket is not readable, the poll() will block for 10ms.  I’m not sure how this helps, since code elsewhere is already polling, but maybe it reduces contention on a lock or improves scheduling somehow.

In any case, though, if the server being tested is sufficiently performant, there will be data to read most of the time, and the poll() is just an extra system call.

I’m not sure that I understand what the “choke it will recv()” comment is referring to.  Presumably if recv() succeeds every time, that’s a good thing.  If recv() is returning EAGAIN every time, that’s not good, but it seems like it would be better to use the polling results from perf_os_waituntilanyreadable() to only read from the readable sockets rather than add additional polling.

**Comment by jelu** [comment]
> If the socket is not readable, the poll() will block for 10ms.

No, `poll()` does not block, it wait 10ms for data and if there is already something to read it will return immediate.

But `poll()` did have problems at first and I think you're running an old enough kernel to have them.

Don't get me wrong, it's great that you have found the issue for your setup. I just would like to confirm the issue on other platforms and sadly we (OARC) do not have the resources like Akamai so I've tried to reach out to others that might already have performance testing setups ready.

**Comment by jelu** [comment]
@nombwelling Just got confirmed results on a Ubuntu 16.04 LTS, same as you, so I will remove the `poll()` tomorrow and make a release.

**Comment by nombwelling** [comment]
Thanks!

Are you also going to remove the identical poll() from the TLS code path?

Also, I notice that there's a lot of duplicated code between various the TCP and TLS send and receive code; would you accept patches to make them share code?

**Comment by jelu** [comment]
You're welcome to make a pull request anytime!
