### ISSUE TITLE
isc-config.sh --libs output is overcomplete

### ISSUE THREAD

**Issue by Habbie** [DNS-OARC/dnsperf#48]
```
/usr/bin/ld: cannot find -lprotobuf-c
/usr/bin/ld: cannot find -ljson-c
collect2: error: ld returned 1 exit status
```

~This should have been detected during `./configure`.~

See actual problem description below.

**Comment by Habbie** [comment]
This ticket is wrong. I'm figuring out what the real problem is now.

**Comment by Habbie** [comment]
Problem:
```
libtool: link: gcc -I. -I.. -pthread -g -O2 -I/usr/include -D_REENTRANT -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -o dnsperf datafile.o dns.o log.o net.o opt.o os.o dnsperf.o  -lbind9 -ldns -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lisccfg -lisc -lcrypto -ldl -lprotobuf-c -lfstrm -lcap -ljson-c -llmdb -lpthread -lm -lGeoIP -L/usr/lib -lxml2 -lssl -lnsl -pthread
/usr/bin/ld: cannot find -lprotobuf-c
/usr/bin/ld: cannot find -ljson-c
collect2: error: ld returned 1 exit status
```

Reason: I do have `/usr/lib/x86_64-linux-gnu/libprotobuf-c.so.1` but not `/usr/lib/x86_64-linux-gnu/libprotobuf-c.so`, because I have not installed libprotobuf-dev-c. However, I am not building anything against libprotobuf-c, I'm building against the various ISC libs. The problem is this:

```
 isc-config.sh --libs dns bind9
-lbind9 -ldns -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lcrypto -lisccfg -lisc -lcrypto -ldl -lprotobuf-c -lfstrm -lcap -ljson-c -llmdb -lpthread -lm -lGeoIP -L/usr/lib -L/usr/lib -lxml2 -L/usr/lib
```

It lists all the libs that those ISC libs have been linked with. This is probably a bug in `isc-config.sh`.

Workaround (works for me on Debian Buster):
```
diff --git a/configure.ac b/configure.ac
index 46dab21..70d10a8 100644
--- a/configure.ac
+++ b/configure.ac
@@ -77,7 +77,7 @@ case "$host_os" in
 esac
 
 AS_VAR_APPEND(CFLAGS, [" `$ac_cv_isc_config --cflags dns bind9`"])
-AS_VAR_APPEND(LDFLAGS, [" `$ac_cv_isc_config --libs dns bind9`"])
+AS_VAR_APPEND(LDFLAGS, [" -lbind9 -ldns -lssl -lnsl -pthread -lisc -lcrypto -lm"])
 
 AC_CHECK_HEADERS([isc/hmacmd5.h isc/hmacsha.h])
```

**Comment by jelu** [comment]
This is a known issue.

The BIND libraries that `dnsperf` uses are really only meant to be used internally in BIND. It's in the planning to remove this dependency.

Better workaround would have been to use the package :)
