### ISSUE TITLE
Error when building on Debian 10

### ISSUE THREAD

**Issue by and0x000** [DNS-OARC/dnsperf#52]
When trying to build dnsperf from git repo on Debian 10 (Buster), I see these errors during the `configure` step:

```
[...]
checking for isc/hmacsha.h... yes
./configure: line 9727: syntax error near unexpected token `libssl,'
./configure: line 9727: `PKG_CHECK_MODULES(libssl, libssl)'
```
Both dependency sets were installed.

Subsequential `make` fails.

**Comment by jelu** [comment]
Do you have `pkgconfig` installed?

**Comment by and0x000** [comment]
I think the package is [pkg-config](https://packages.debian.org/buster/pkg-config) in Debian and Ubuntu, with a dash.

No, did not have it installed. Installed it, cleaned the checked out repo and repeated the steps for building -> solved.

Thank you very much.
