### ISSUE TITLE
get error when test coredns with tcp

### ISSUE THREAD

**Issue by traderway** [DNS-OARC/dnsperf#63]
root@n1:~# **/usr/local/bin/dnsperf -d /tmp/dnsperf_file.txt -s 10.1.1.63 -m tcp -p 53**
DNS Performance Testing Tool
Version 2.3.2

[Status] Command line: dnsperf -d /tmp/dnsperf_file.txt -s 10.1.1.63 -m tcp -p 53
[Status] Sending queries (to 10.1.1.63)
[Status] Started at: Sat Dec  7 15:15:58 2019
[Status] Stopping after 1 run through file
[Status] Testing complete (end of file)

Statistics:

  Queries sent:         123
  Queries completed:    123 (100.00%)
  Queries lost:         0 (0.00%)

  Response codes:       NOERROR 123 (100.00%)
  Average packet size:  request 36, response 71
  Run time (s):         0.712423
  Queries per second:   172.650237

  Average Latency (s):  0.339607 (min 0.009501, max 0.573167)
  Latency StdDev (s):   0.182204

root@n1:~# **/usr/local/bin/dnsperf -d /tmp/dnsperf_file.txt -s 10.1.1.63 -m tcp -p 53 -l 60**
DNS Performance Testing Tool
Version 2.3.2

[Status] Command line: dnsperf -d /tmp/dnsperf_file.txt -s 10.1.1.63 -m tcp -p 53 -l 60
[Status] Sending queries (to 10.1.1.63)
[Status] Started at: Sat Dec  7 15:16:04 2019
[Status] Stopping after 60.000000 seconds
Warning: received a response with an unexpected (maybe timed out) id: 127
Error: failed to receive packet: Connection reset by peer

**how can  test dns with tcp ?**

**Comment by traderway** [comment]
[Status] Command line: dnsperf -d /tmp/dnsperf_file.txt -s 10.1.1.63 -m tcp -p 53 -n 1000
[Status] Sending queries (to 10.1.1.63)
[Status] Started at: Sat Dec  7 15:45:41 2019
[Status] Stopping after 1000 runs through file
Warning: received a response with an unexpected (maybe timed out) id: 127
Error: failed to receive packet: Connection reset by peer
root@n1:~# /usr/local/bin/dnsperf -d /tmp/dnsperf_file.txt -s 10.1.1.63 -m tcp -p 53 -n 10000
DNS Performance Testing Tool
Version 2.3.2

[Status] Command line: dnsperf -d /tmp/dnsperf_file.txt -s 10.1.1.63 -m tcp -p 53 -n 10000
[Status] Sending queries (to 10.1.1.63)
[Status] Started at: Sat Dec  7 15:45:48 2019
[Status] Stopping after 10000 runs through file
Warning: received a response with an unexpected (maybe timed out) id: 127
Error: failed to receive packet: Connection reset by peer

**Comment by traderway** [comment]
[Status] Command line: dnsperf -d /tmp/dnsperf_file.txt -s 10.1.1.63 -m tcp -p 53 -n 1
[Status] Sending queries (to 10.1.1.63)
[Status] Started at: Sat Dec  7 15:48:19 2019
[Status] Stopping after 1 run through file
[Status] Testing complete (end of file)

Statistics:

  Queries sent:         123
  Queries completed:    123 (100.00%)
  Queries lost:         0 (0.00%)

  Response codes:       NOERROR 123 (100.00%)
  Average packet size:  request 36, response 71
  Run time (s):         0.752382
  Queries per second:   163.480785

  Average Latency (s):  0.362258 (min 0.008832, max 0.607325)
  Latency StdDev (s):   0.194984

root@n1:~# /usr/local/bin/dnsperf -d /tmp/dnsperf_file.txt -s 10.1.1.63 -m tcp -p 53 -n 2
DNS Performance Testing Tool
Version 2.3.2

[Status] Command line: dnsperf -d /tmp/dnsperf_file.txt -s 10.1.1.63 -m tcp -p 53 -n 2
[Status] Sending queries (to 10.1.1.63)
[Status] Started at: Sat Dec  7 15:48:24 2019
[Status] Stopping after 2 runs through file
Warning: received a response with an unexpected (maybe timed out) id: 127
Error: failed to receive packet: Connection reset by peer

**Comment by traderway** [comment]
I found the second round will get error.

**Comment by jelu** [comment]
Works fine with my local DNS server using a file with 130 queries and running it twice:
```
$ wc -l dns
130 dns
$ src/dnsperf -d dns -s 172.17.0.1 -m tcp -n 2
DNS Performance Testing Tool
Version 2.3.2

[Status] Command line: dnsperf -d dns -s 172.17.0.1 -m tcp -n 2
[Status] Sending queries (to 172.17.0.1)
[Status] Started at: Thu Dec 19 17:35:00 2019
[Status] Stopping after 2 runs through file
[Status] Testing complete (end of file)

Statistics:

  Queries sent:         260
  Queries completed:    260 (100.00%)
  Queries lost:         0 (0.00%)

  Response codes:       NOERROR 260 (100.00%)
  Average packet size:  request 28, response 44
  Run time (s):         0.053278
  Queries per second:   4880.063065

  Average Latency (s):  0.002938 (min 0.000032, max 0.044449)
  Latency StdDev (s):   0.008785
```

Are you perhaps rate limited or denied from 10.1.1.63?

**Comment by jelu** [comment]
Oh, interesting, I'm getting the same errors when trying against Google public DNS and they are responding out of order (it sends DNS ID 1,2,3,4,5 but receives 2,5,1,3,4 etc).

What are you running at 10.1.1.63?

**Comment by jelu** [comment]
OK, the problem you're having is that the connection is reset (by the DNS server) and that is currently treated as a fatal error.

This can happen if the DNS server is rate limiting or in other ways feel that you're sending to much.

I'm going to change so that it's not fatal anymore but there is no reconnection code in yet so if it happens it will just timeout. You can try the develop branch soon or the pre-release packages in a bit.

```
$ src/dnsperf -d dns -s 8.8.8.8 -m tcp -n 1
DNS Performance Testing Tool
Version 2.3.2

[Status] Command line: dnsperf -d dns -s 8.8.8.8 -m tcp -n 1
[Status] Sending queries (to 8.8.8.8)
[Status] Started at: Fri Dec 20 10:12:33 2019
[Status] Stopping after 1 run through file
[Timeout] Query timed out: msg id 60
[Timeout] Query timed out: msg id 61
[Timeout] Query timed out: msg id 62
[Timeout] Query timed out: msg id 63
[Timeout] Query timed out: msg id 64
[Timeout] Query timed out: msg id 65
[Timeout] Query timed out: msg id 66
[Timeout] Query timed out: msg id 67
[Timeout] Query timed out: msg id 68
[Timeout] Query timed out: msg id 69
[Timeout] Query timed out: msg id 70
[Timeout] Query timed out: msg id 71
[Timeout] Query timed out: msg id 72
[Timeout] Query timed out: msg id 73
[Timeout] Query timed out: msg id 74
[Timeout] Query timed out: msg id 75
[Timeout] Query timed out: msg id 76
[Timeout] Query timed out: msg id 77
[Timeout] Query timed out: msg id 78
[Timeout] Query timed out: msg id 79
[Timeout] Query timed out: msg id 80
[Timeout] Query timed out: msg id 81
[Timeout] Query timed out: msg id 82
[Timeout] Query timed out: msg id 83
[Timeout] Query timed out: msg id 84
[Timeout] Query timed out: msg id 85
[Timeout] Query timed out: msg id 86
[Timeout] Query timed out: msg id 87
[Timeout] Query timed out: msg id 88
[Timeout] Query timed out: msg id 89
[Timeout] Query timed out: msg id 90
[Timeout] Query timed out: msg id 91
[Timeout] Query timed out: msg id 92
[Timeout] Query timed out: msg id 93
[Timeout] Query timed out: msg id 94
[Timeout] Query timed out: msg id 95
[Timeout] Query timed out: msg id 96
[Timeout] Query timed out: msg id 97
[Timeout] Query timed out: msg id 98
[Timeout] Query timed out: msg id 99
[Timeout] Query timed out: msg id 100
[Timeout] Query timed out: msg id 101
[Timeout] Query timed out: msg id 102
[Timeout] Query timed out: msg id 103
[Timeout] Query timed out: msg id 104
[Timeout] Query timed out: msg id 105
[Timeout] Query timed out: msg id 106
[Timeout] Query timed out: msg id 107
[Timeout] Query timed out: msg id 108
[Timeout] Query timed out: msg id 109
[Timeout] Query timed out: msg id 110
[Timeout] Query timed out: msg id 111
[Timeout] Query timed out: msg id 112
[Timeout] Query timed out: msg id 113
[Timeout] Query timed out: msg id 114
[Timeout] Query timed out: msg id 115
[Timeout] Query timed out: msg id 116
[Timeout] Query timed out: msg id 117
[Timeout] Query timed out: msg id 118
[Timeout] Query timed out: msg id 119
[Timeout] Query timed out: msg id 120
[Timeout] Query timed out: msg id 121
[Timeout] Query timed out: msg id 122
[Timeout] Query timed out: msg id 123
[Timeout] Query timed out: msg id 124
[Timeout] Query timed out: msg id 125
[Timeout] Query timed out: msg id 126
[Timeout] Query timed out: msg id 127
[Timeout] Query timed out: msg id 128
[Timeout] Query timed out: msg id 129
[Status] Testing complete (end of file)

Statistics:

  Queries sent:         130
  Queries completed:    60 (46.15%)
  Queries lost:         70 (53.85%)

  Response codes:       NOERROR 60 (100.00%)
  Average packet size:  request 28, response 44
  Run time (s):         0.010302
  Queries per second:   5824.111823

  Average Latency (s):  0.003628 (min 0.001778, max 0.004494)
  Latency StdDev (s):   0.000507
```

**Comment by traderway** [comment]
sorry 
I deploy a coredns on 10.1.1.63 and do dns tcp bench test with dnsperf, 
I found number recored in test document(./test.txt) reach 129(>128) then get error.
dnsperf -d ./test.txt -s 10.1.1.63 -m tcp -p 53
the desployment as following:



## how to desploy coredns server for dns service
## coredns config file
cat << _EOF_ > /tmp/coredns/Corefile
test.ai:53 {
    log
    errors
    #cache 60
    reload 1m
    file /tmp/test.ai
}
_EOF

## coredns config file for dns resolve
## you can change all the ip of the record
cat << _EOF_ > /tmp/coredns/test.ai

$ORIGIN test.ai.
$TTL 60s
@       60 IN   SOA dns.test.ai. dnsadmin.test.ai. (
                2017042745 ; serial
                7200       ; refresh (2 hours)
                3600       ; retry (1 hour)
                1209600    ; expire (2 weeks)
                3600       ; minimum (1 hour)
                )

    60 IN NS dns.test.ai.

dns.test.ai. IN A 10.1.1.63
ntp1.test.ai. IN A 10.1.1.64
ntp2.test.ai. IN A 10.1.1.65
_EOF

# download coredns
docker pull coredns/coredns

# run coredns with docker
docker run -d --name coredns \
            --restart always \
            --log-opt max-size=300M \
            --log-opt max-file=2 \
            --net host \
            -p 53/tcp \
            -p 53/udp \
            -v /etc/localtime:/etc/localtime:ro \
            -v /etc/timezone:/etc/timezone:ro \
            -v /tmp/coredns:/mnt/coredns \
            -w mnt/coredns \
            coredns/coredns:latest \
            -conf /mnt/coredns/Corefile -dns.port 53

**Comment by traderway** [comment]
[Status] Command line: dnsperf -d /tmp/dnsperf_file.txt -s 10.1.1.63 -m tcp -p 53 -l 3000
[Status] Sending queries (to 10.1.1.63)
[Status] Started at: Sat Dec 21 15:03:08 2019
[Status] Stopping after 3000.000000 seconds
[Timeout] Query timed out: msg id 128
[Timeout] Query timed out: msg id 129
[Timeout] Query timed out: msg id 130
[Timeout] Query timed out: msg id 131
[Timeout] Query timed out: msg id 132
[Timeout] Query timed out: msg id 133
[Timeout] Query timed out: msg id 134
[Timeout] Query timed out: msg id 135
[Timeout] Query timed out: msg id 136
[Timeout] Query timed out: msg id 137
[Timeout] Query timed out: msg id 138
[Timeout] Query timed out: msg id 139
[Timeout] Query timed out: msg id 140
[Timeout] Query timed out: msg id 141
[Timeout] Query timed out: msg id 142
[Timeout] Query timed out: msg id 143
[Timeout] Query timed out: msg id 144
[Timeout] Query timed out: msg id 145
[Timeout] Query timed out: msg id 146
[Timeout] Query timed out: msg id 147
[Timeout] Query timed out: msg id 148
[Timeout] Query timed out: msg id 149
[Timeout] Query timed out: msg id 150

[Status] Command line: dnsperf -d /tmp/dnsperf_file.txt -s 10.1.1.63 -m tcp -p 53 -l 30
[Status] Sending queries (to 10.1.1.63)
[Status] Started at: Sat Dec 21 15:08:32 2019
[Status] Stopping after 30.000000 seconds
[Timeout] Query timed out: msg id 128
root@k1:~# /usr/local/bin/dnsperf -d /tmp/dnsperf_file.txt -s 10.1.1.63 -m tcp -p 53
DNS Performance Testing Tool
Version 2.3.2

[Status] Command line: dnsperf -d /tmp/dnsperf_file.txt -s 10.1.1.63 -m tcp -p 53
[Status] Sending queries (to 10.1.1.63)
[Status] Started at: Sat Dec 21 15:08:51 2019
[Status] Stopping after 1 run through file
[Status] Testing complete (end of file)

Statistics:

  Queries sent:         121
  Queries completed:    121 (100.00%)
  Queries lost:         0 (0.00%)

  Response codes:       NOERROR 121 (100.00%)
  Average packet size:  request 39, response 76
  Run time (s):         0.016743
  Queries per second:   7226.900794

  Average Latency (s):  0.005151 (min 0.000387, max 0.011335)
  Latency StdDev (s):   0.003241

root@k1:~# cat /tmp/dnsperf_file.txt | wc -l
121

**Comment by traderway** [comment]
test with unbound and tcp, it ok. but test with coredns and tcp , then got error.

**Comment by traderway** [comment]
root@k3:~# /usr/local/bin/dnsperf -d /tmp/dnsperf_file.txt -s 127.0.0.1 -m tcp -p 53 -l 30 -c 16 -T 1 
DNS Performance Testing Tool
Version 2.3.2

[Status] Command line: dnsperf -d /tmp/dnsperf_file.txt -s 127.0.0.1 -m tcp -p 53 -l 30 -c 16 -T 1
[Status] Sending queries (to 127.0.0.1)
[Status] Started at: Sat Dec 21 15:14:47 2019
[Status] Stopping after 30.000000 seconds
root@k3:~# /usr/local/bin/dnsperf -d /tmp/dnsperf_file.txt -s 127.0.0.1 -m tcp -p 53 -l 30
DNS Performance Testing Tool
Version 2.3.2

[Status] Command line: dnsperf -d /tmp/dnsperf_file.txt -s 127.0.0.1 -m tcp -p 53 -l 30
[Status] Sending queries (to 127.0.0.1)
[Status] Started at: Sat Dec 21 15:14:54 2019
[Status] Stopping after 30.000000 seconds
[Timeout] Query timed out: msg id 128
[Timeout] Query timed out: msg id 129
[Timeout] Query timed out: msg id 130
[Timeout] Query timed out: msg id 131
[Timeout] Query timed out: msg id 132
root@k3:~# /usr/local/bin/dnsperf -d /tmp/dnsperf_file.txt -s 127.0.0.1 -m tcp -p 53 -l 30 -c 16
DNS Performance Testing Tool
Version 2.3.2

[Status] Command line: dnsperf -d /tmp/dnsperf_file.txt -s 127.0.0.1 -m tcp -p 53 -l 30 -c 16
[Status] Sending queries (to 127.0.0.1)
[Status] Started at: Sat Dec 21 15:15:06 2019
[Status] Stopping after 30.000000 seconds
root@k3:~# /usr/local/bin/dnsperf -d /tmp/dnsperf_file.txt -s 127.0.0.1 -m tcp -p 53 -l 30 -c 16 -T 1
DNS Performance Testing Tool
Version 2.3.2

[Status] Command line: dnsperf -d /tmp/dnsperf_file.txt -s 127.0.0.1 -m tcp -p 53 -l 30 -c 16 -T 1
[Status] Sending queries (to 127.0.0.1)
[Status] Started at: Sat Dec 21 15:15:13 2019
[Status] Stopping after 30.000000 seconds

**Comment by jelu** [comment]
Does all these tests work with Unbound?

**Comment by jelu** [comment]
Please try the new develop branch, also please try and describe problems because it's hard to understand what you feel is wrong with just console output.
