### ISSUE TITLE
dnsperf 2.3.3 failed to build on osx

### ISSUE THREAD

**Issue by chenrui333** [DNS-OARC/dnsperf#70]
relates to https://github.com/Homebrew/homebrew-core/pull/54450

Current issue I saw is:

```
checking for BIND 9 libraries... checking for isc-config.sh... no
configure: error: BIND 9 libraries must be installed
```

The logs are in GHA runs, https://github.com/Homebrew/homebrew-core/runs/659210419

**Comment by jelu** [comment]
Install the correct dependencies.

**Comment by jelu** [comment]
And frankly, if you expect more help then this, try explaining what the problem is instead of pasting a log that clearly states the problem.
