### ISSUE TITLE
Remove dependency on internal BIND libraries

### ISSUE THREAD

**Issue by jelu** [DNS-OARC/dnsperf#73]
As of BIND 9.16, their internal libraries are not for public consumption and even if #72 works for now it might break in the future. Best would be to remove the dependency but it will require a lot of rewriting.

TODO:
- [x] replace ISC linked lists
- [x] transition `isc_result_t`
- [x] remove dependencies in `opt.c`
- [x] remove dependencies in `net.c` and isc_net* in `dnsperf.c`
- [x] remove dependencies in `datafile.c` and change usage in `dnsperf.c` / `resperf.c`
- [x] disable HMAC code
- [x] disable dynamic update code
- [x] disable EDNS option code
- [x] remove dependencies in `dns.c` and change usage `dnsperf.c` / `resperf.c`
- [x] remove dependencies in `result.h`
- [x] remove bind dependency from configure and packages
- [x] add EDNS option and re-enable tests
- [x] add HMAC support using OpenSSL and re-enable tests
- [ ] add dynamic update support using ldns

Also see #67.

**Comment by pemensik** [comment]
Is it already clear what parts need replacements and what they should be replaced with? Is a ldns library good alternative?

**Comment by jelu** [comment]
No, I've not had any time (or know when I will) to look at what needs replacement but a fair guess is all the DNS wire-format handling, basically anything `isc_*`. Sure, ldns or libknot are good alternatives.

**Comment by pspacek** [comment]
I would say it is better to base new version on dnsjit - it has all DNS parsing magic inside + it has components for DNS-over-TCP/TLS/HTTPS2. Or maybe dnsperf will end up as thin wrapper around DNS Shotgun :thinking:

**Comment by jelu** [comment]
Please, if anyone is working on this let me know ASAP. There is things happening in the background that I don't think I can share yet but it would be sad if we have multiple parties working on the same thing at the same time.

> I would say it is better to base new version on dnsjit - it has all DNS parsing magic inside + it has components for DNS-over-TCP/TLS/HTTPS2.

I don't agree, there is limitations with dnsjit/LuaJIT, both OS and CPU arch. And `dnssim` is really DNS shotgun, I don't know if it's easy usable for others with other scenarios and use-cases.

> Or maybe dnsperf will end up as thin wrapper around DNS Shotgun

It's too early to say if that could work, DNS shotgun is not an OARC project either.

**Comment by jelu** [comment]
This work is scheduled for Q4 2020.

**Comment by jelu** [comment]
> - Remove BIND as a dependency!

:partying_face: :tada: :fireworks:
