### ISSUE TITLE
Flag to clear RD bit in dnsperf

### ISSUE THREAD

**Issue by chantra** [DNS-OARC/dnsperf#95]
When testing against an authoritative server it can be useful to clear RD bit as it is not really supposed to be set when a recursive server queries an auth server and an auth server may decide to REFUSED responding if RD is set.

https://github.com/DNS-OARC/dnsperf/blob/71e810fdda1225224774a743a286c7cfbb016a41/src/dns.c#L1024

seems to force set it.
Any objection about making an option to clear it?

**Comment by jelu** [comment]
No objections from me as long as it's a long options since short ones tend to run out quite quickly.

Or if you want to add it as meta options to the datafile, like `%flags +rd`, `%flags -rd` etc, that would be kinda useful and extendable.

**Comment by chantra** [comment]
@jelu  is there any current support for meta data in the datafile?

**Comment by jelu** [comment]
@chantra No, nothing like this exists today. But the dynamic update has similar structure.

Btw, just to clarify my initial response, you're free to send PRs with any change. You could also fund the development if you wish, please see https://www.dns-oarc.net/oarc/software if so.
